version: "3"

services:
  yarn:
    image: node:16.0.0
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    entrypoint: yarn
    command: --help
    volumes:
      - .:/home/node
  npm:
    image: node:16.0.0
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    entrypoint: npm
    command: --help
    volumes:
      - .:/home/node



