name: Build

on:
  pull_request:
    branches:
      - latest
      - next

  push:
    branches:
      - latest
      - next

jobs:
  build:
    name: Check that the project can be built
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Build
        run: make build
