name: Example

on:
  pull_request:
    branches:
      - next

  push:
    branches:
      - next

jobs:
  example:
    name: Check that the package can be installed and used
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Build
        run: make build

      - name: Pack
        run: make pack

      - name: Package Install
        run: make packinstall

      - name: Example
        run: make example
