name: Test

on:
  pull_request:
    branches:
      - latest
      - next

  push:
    branches:
      - latest
      - next

jobs:
  test:
    name: Check that tests cover the project
    runs-on: ubuntu-21.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Test
        run: make test
